name: wf-multi-job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: check system info ubuntu
        run: cat /etc/os-release

  windows-job:
    runs-on: windows-latest
    steps:
      - name: check system info windows
        run: systeminfo

  macos-job:
    runs-on: macos-latest
    steps:
      - name: check system info for macos
        run: sw_vers
